In [2]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
import seaborn as sns
from category_encoders import *

In [53]:
data = pd.read_excel("car_sales_mod (1).xlsx")
data.head(15)

,manufact,model,sales,type,price,engine_s,horsepow,wheelbas,width,length,curb_wgt,fuel_cap,mpg,lnsales,Partition
0,Acura,Integra,16.919,0,21.500,1.8,140,101.2,67.3,172.4,2.639,13.2,28.0,2.828437,0
1,Acura,TL,39.384,0,28.400,3.2,225,108.1,70.3,192.9,3.517,17.2,25.0,3.673360,0
2,Acura,RL,8.588,0,42.000,3.5,210,114.6,71.4,196.6,3.850,18.0,22.0,2.150366,0
3,Audi,A4,20.397,0,23.990,1.8,150,102.6,68.2,178.0,2.998,16.4,27.0,3.015388,0
4,Audi,A6,18.780,0,33.950,2.8,200,108.7,76.1,192.0,3.561,18.5,22.0,2.932792,0
5,Audi,A8,1.380,0,62.000,4.2,310,113.0,74.0,198.2,3.902,23.7,21.0,0.322083,0
6,BMW,323i,19.747,0,26.990,2.5,170,107.3,68.4,176.0,3.179,16.6,26.1,2.983002,0
7,BMW,328i,9.231,0,33.400,2.8,193,107.3,68.5,176.0,3.197,16.6,24.0,2.222567,0
8,BMW,528i,17.527,0,38.900,2.8,193,111.4,70.9,188.0,3.472,18.5,24.8,2.863743,0
9,Buick,Century,91.561,0,21.975,3.1,175,109.0,72.7,194.6,3.368,17.5,25.0,4.517005,0
10,Buick,Regal,39.350,0,25.300,3.8,240,109.0,72.7,196.2,3.543,17.5,23.0,3.672496,0
11,Buick,Park Avenue,27.851,0,31.965,3.8,205,113.8,74.7,206.8,3.778,18.5,24.0,3.326869,0
12,Buick,LeSabre,83.257,0,27.885,3.8,205,112.2,73.5,200.0,3.591,17.5,25.0,4.421932,0
13,Cadillac,DeVille,63.729,0,39.895,4.6,275,115.3,74.5,207.2,3.978,18.5,22.0,4.154640,0
14,Cadillac,Eldorado,6.536,0,39.665,4.6,275,108.0,75.5,200.6,3.843,19.0,22.0,1.877325,0

In [4]:
data.isnull().sum() # null 값 확인

manufact     0
model        0
sales        0
type         0
price        0
engine_s     0
horsepow     0
wheelbas     0
width        0
length       0
curb_wgt     0
fuel_cap     0
mpg          0
lnsales      0
Partition    0
dtype: int64

In [5]:
data.describe() #해당 데이터의 기초통계 확인

,sales,type,price,engine_s,horsepow,wheelbas,width,length,curb_wgt,fuel_cap,mpg,lnsales,Partition
count,154.000000,154.000000,154.000000,154.000000,154.000000,154.000000,154.000000,154.00000,154.000000,154.000000,154.000000,154.000000,154.000000
mean,52.666097,0.266234,27.338552,3.042208,183.987013,107.422078,71.094805,186.98961,3.380649,17.914935,23.999351,3.246284,0.012987
std,68.753988,0.443430,14.342627,1.051036,57.144009,7.670180,3.467549,13.41863,0.639996,3.942541,4.637197,1.376120,0.113588
min,0.000000,0.000000,9.235000,1.000000,55.000000,92.600000,62.600000,149.40000,1.895000,10.300000,15.000000,-2.207275,0.000000
25%,13.006750,0.000000,17.953750,2.300000,146.500000,103.000000,68.325000,177.42500,2.960250,15.725000,21.000000,2.565267,0.000000
50%,28.413500,0.000000,22.747000,3.000000,175.000000,107.000000,70.400000,186.65000,3.336000,17.200000,24.000000,3.346668,0.000000
75%,67.640000,1.000000,31.956250,3.500000,210.000000,112.050000,73.100000,194.80000,3.822500,19.725000,26.000000,4.214167,0.000000
max,540.561000,1.000000,85.500000,8.000000,450.000000,138.700000,79.900000,224.50000,5.572000,32.000000,46.000000,6.292607,1.000000

In [6]:
data.corr()

,sales,type,price,engine_s,horsepow,wheelbas,width,length,curb_wgt,fuel_cap,mpg,lnsales,Partition
sales,1.000000,0.234259,-0.300648,0.032629,-0.178349,0.357816,0.140716,0.262458,0.003267,0.095075,-0.041310,0.724950,-0.088154
type,0.234259,1.000000,-0.034819,0.274439,0.020514,0.396430,0.272100,0.152601,0.536738,0.592520,-0.540268,0.244620,0.060669
price,-0.300648,-0.034819,1.000000,0.623202,0.833875,0.109672,0.331800,0.157015,0.527610,0.423614,-0.464079,-0.531513,0.004104
engine_s,0.032629,0.274439,0.623202,1.000000,0.837499,0.471041,0.693913,0.545329,0.757793,0.670831,-0.719197,-0.113026,-0.059368
horsepow,-0.178349,0.020514,0.833875,0.837499,1.000000,0.279824,0.533392,0.390012,0.601134,0.514779,-0.621269,-0.335659,-0.125842
wheelbas,0.357816,0.396430,0.109672,0.471041,0.279824,1.000000,0.679198,0.838640,0.647729,0.652516,-0.462228,0.278197,0.009421
width,0.140716,0.272100,0.331800,0.693913,0.533392,0.679198,1.000000,0.704855,0.727306,0.660855,-0.576633,0.031045,0.015107
length,0.262458,0.152601,0.157015,0.545329,0.390012,0.838640,0.704855,1.000000,0.625423,0.573810,-0.439267,0.219128,-0.045365
curb_wgt,0.003267,0.536738,0.527610,0.757793,0.601134,0.647729,0.727306,0.625423,1.000000,0.852802,-0.763550,-0.055554,0.061021
fuel_cap,0.095075,0.592520,0.423614,0.670831,0.514779,0.652516,0.660855,0.573810,0.852802,1.000000,-0.781943,0.011798,-0.098222
mpg,-0.041310,-0.540268,-0.464079,-0.719197,-0.621269,-0.462228,-0.576633,-0.439267,-0.763550,-0.781943,1.000000,0.026426,0.297822
lnsales,0.724950,0.244620,-0.531513,-0.113026,-0.335659,0.278197,0.031045,0.219128,-0.055554,0.011798,0.026426,1.000000,-0.271480
Partition,-0.088154,0.060669,0.004104,-0.059368,-0.125842,0.009421,0.015107,-0.045365,0.061021,-0.098222,0.297822,-0.271480,1.000000

In [7]:
data.skew()

sales        3.377507
type         1.068228
price        1.781243
engine_s     1.106651
horsepow     1.019296
wheelbas     0.993635
width        0.518655
length      -0.005923
curb_wgt     0.703270
fuel_cap     1.109196
mpg          1.166332
lnsales     -0.812032
Partition    8.687943
dtype: float64

In [16]:
old_data = data[data['manufact']!="UD"].drop(['model','sales','lnsales','Partition','type'],1)
new_data = data[data['manufact']=="UD"].drop(['model','sales','lnsales','Partition','type'],1).drop(['manufact'],1)

In [13]:
X = old_data.drop(['manufact'],1).values
y = old_data['manufact'].values

In [20]:
from sklearn.neighbors import KNeighborsClassifier  
KNN_model = KNeighborsClassifier(n_neighbors=5,
                                 metric='euclidean',
                                weights='distance') #가까운 이웃일수록 가중치 둠
KNN_model.fit(X,y)
new_pred = KNN_model.predict(new_data)

In [21]:
new_pred

array(['Saturn', 'Volvo'], dtype=object)

In [30]:
new_data['manufact'] = new_pred

In [71]:
newCar = list(new_data.loc[152][:-1])
newTruck = list(new_data.loc[153][:-1])

#### 제조사 하위 브랜드 간 유사도 거리 구하기(newCar-Saturn / newTruck-Volvo)

In [42]:
def euclidean(v1, v2):
    return sum((p-q)**2 for p, q in zip(v1, v2)) ** .5

In [72]:
Saturn = data[data['manufact']=="Saturn"].drop(['sales','lnsales','Partition','type'],1)
Volvo = data[data['manufact']=="Volvo"].drop(['sales','lnsales','Partition','type'],1)

In [73]:
Saturn

,manufact,model,price,engine_s,horsepow,wheelbas,width,length,curb_wgt,fuel_cap,mpg
124,Saturn,SL,10.685,1.9,100,102.4,66.4,176.9,2.332,12.1,33.0
125,Saturn,SC,12.535,1.9,100,102.4,66.4,180.0,2.367,12.1,33.0
126,Saturn,SW,14.290,1.9,124,102.4,66.4,176.9,2.452,12.1,31.0
127,Saturn,LW,18.835,2.2,137,106.5,69.0,190.4,3.075,13.1,27.0
128,Saturn,LS,15.010,2.2,137,106.5,69.0,190.4,2.910,13.1,28.0

In [97]:
euc_list = []
v1 = newCar
for i in Saturn.values:
    v2 = i[2:]
    eu = euclidean(v1,v2)
    print("model:",i[1])
    print(eu)
    print("======================")
    euc_list.append(eu)
print("최소 유사도 거리:",min(euc_list))

model: SL
29.72531286630975
======================
model: SC
29.467786649153002
======================
model: SW
51.01455184552737
======================
model: LW
65.79865252419688
======================
model: LS
65.78343700354976
======================
최소 유사도 거리: 29.467786649153002

In [96]:
euc_list = []
v1 = newTruck
for i in Volvo.values:
    v2 = i[2:]
    eu = euclidean(v1,v2)
    print("model:",i[1])
    print(eu)
    print("======================")
    euc_list.append(eu)
print("최소 유사도 거리:",min(euc_list))

model: S40
21.375923371868648
======================
model: V40
20.885381394650192
======================
model: S70
10.74011173126239
======================
model: V70
9.903534772998986
======================
model: C70
70.332301604597
======================
model: S80
34.51397490872357
======================
최소 유사도 거리: 9.903534772998986

#### ROW152_TYPE=1(Truck)인 경우만 고려하기

In [357]:
data

,manufact,model,sales,type,price,engine_s,horsepow,wheelbas,width,length,curb_wgt,fuel_cap,mpg,lnsales,Partition
0,Acura,Integra,16.919,0,21.500,1.8,140,101.2,67.3,172.4,2.639,13.2,28.0,2.828437,0
1,Acura,TL,39.384,0,28.400,3.2,225,108.1,70.3,192.9,3.517,17.2,25.0,3.673360,0
2,Acura,RL,8.588,0,42.000,3.5,210,114.6,71.4,196.6,3.850,18.0,22.0,2.150366,0
3,Audi,A4,20.397,0,23.990,1.8,150,102.6,68.2,178.0,2.998,16.4,27.0,3.015388,0
4,Audi,A6,18.780,0,33.950,2.8,200,108.7,76.1,192.0,3.561,18.5,22.0,2.932792,0
5,Audi,A8,1.380,0,62.000,4.2,310,113.0,74.0,198.2,3.902,23.7,21.0,0.322083,0
6,BMW,323i,19.747,0,26.990,2.5,170,107.3,68.4,176.0,3.179,16.6,26.1,2.983002,0
7,BMW,328i,9.231,0,33.400,2.8,193,107.3,68.5,176.0,3.197,16.6,24.0,2.222567,0
8,BMW,528i,17.527,0,38.900,2.8,193,111.4,70.9,188.0,3.472,18.5,24.8,2.863743,0
9,Buick,Century,91.561,0,21.975,3.1,175,109.0,72.7,194.6,3.368,17.5,25.0,4.517005,0
10,Buick,Regal,39.350,0,25.300,3.8,240,109.0,72.7,196.2,3.543,17.5,23.0,3.672496,0
11,Buick,Park Avenue,27.851,0,31.965,3.8,205,113.8,74.7,206.8,3.778,18.5,24.0,3.326869,0
12,Buick,LeSabre,83.257,0,27.885,3.8,205,112.2,73.5,200.0,3.591,17.5,25.0,4.421932,0
13,Cadillac,DeVille,63.729,0,39.895,4.6,275,115.3,74.5,207.2,3.978,18.5,22.0,4.154640,0
14,Cadillac,Eldorado,6.536,0,39.665,4.6,275,108.0,75.5,200.6,3.843,19.0,22.0,1.877325,0
15,Cadillac,Catera,11.185,0,31.010,3.0,200,107.4,70.3,194.8,3.770,18.0,22.0,2.414574,0
16,Cadillac,Escalade,14.785,1,46.225,5.7,255,117.5,77.0,201.2,5.572,30.0,15.0,2.693613,0
17,Chevrolet,Cavalier,145.519,0,13.260,2.2,115,104.1,67.9,180.9,2.676,14.3,27.0,4.980307,0
18,Chevrolet,Malibu,135.126,0,16.535,3.1,170,107.0,69.4,190.4,3.051,15.0,25.0,4.906208,0
19,Chevrolet,Lumina,24.629,0,18.890,3.1,175,107.5,72.5,200.9,3.330,16.6,25.0,3.203925,0
20,Chevrolet,Monte Carlo,42.593,0,19.390,3.4,180,110.5,72.7,197.9,3.340,17.0,27.0,3.751690,0
21,Chevrolet,Camaro,26.402,0,24.340,3.8,200,101.1,74.1,193.2,3.500,16.8,25.0,3.273440,0
22,Chevrolet,Corvette,17.947,0,45.705,5.7,345,104.5,73.6,179.7,3.210,19.1,22.0,2.887423,0
23,Chevrolet,Prizm,32.299,0,13.960,1.8,120,97.1,66.7,174.3,2.398,13.2,33.0,3.475036,0
24,Chevrolet,Metro,21.855,0,9.235,1.0,55,93.1,62.6,149.4,1.895,10.3,45.0,3.084430,0
25,Chevrolet,Impala,107.995,0,18.890,3.4,180,110.5,73.0,200.0,3.389,17.0,27.0,4.682085,0
26,Chrysler,Sebring Coupe,7.854,0,19.840,2.5,163,103.7,69.7,190.9,2.967,15.9,24.0,2.061023,0
27,Chrysler,Sebring Conv.,32.775,0,24.495,2.5,168,106.0,69.2,193.0,3.332,16.0,24.0,3.489666,0
28,Chrysler,Concorde,31.148,0,22.245,2.7,200,113.0,74.4,209.1,3.452,17.0,26.0,3.438750,0
29,Chrysler,Cirrus,32.306,0,16.480,2.0,132,108.0,71.0,186.0,2.911,16.0,27.0,3.475253,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
124,Saturn,SL,80.620,0,10.685,1.9,100,102.4,66.4,176.9,2.332,12.1,33.0,4.389747,0
125,Saturn,SC,24.546,0,12.535,1.9,100,102.4,66.4,180.0,2.367,12.1,33.0,3.200549,0
126,Saturn,SW,5.223,0,14.290,1.9,124,102.4,66.4,176.9,2.452,12.1,31.0,1.653072,0
127,Saturn,LW,8.472,0,18.835,2.2,137,106.5,69.0,190.4,3.075,13.1,27.0,2.136767,0
128,Saturn,LS,49.989,0,15.010,2.2,137,106.5,69.0,190.4,2.910,13.1,28.0,3.911803,0
129,Subaru,Outback,47.107,0,22.695,2.5,165,103.5,67.5,185.8,3.415,16.9,25.0,3.852422,0
130,Subaru,Forester,33.028,1,20.095,2.5,165,99.4,68.3,175.2,3.125,15.9,24.0,3.497356,0
131,Toyota,Corolla,142.535,0,13.108,1.8,120,97.0,66.7,174.0,2.420,13.2,33.0,4.959588,0
132,Toyota,Camry,247.994,0,17.518,2.2,133,105.2,70.1,188.5,2.998,18.5,27.0,5.513405,0
133,Toyota,Avalon,63.849,0,25.545,3.0,210,107.1,71.7,191.9,3.417,18.5,26.0,4.156521,0
134,Toyota,Celica,33.269,0,16.875,1.8,140,102.4,68.3,170.5,2.425,14.5,31.0,3.504626,0
135,Toyota,Tacoma,84.087,1,11.528,2.4,142,103.3,66.5,178.7,2.580,15.1,23.0,4.431852,0
136,Toyota,Sienna,65.119,1,22.368,3.0,194,114.2,73.4,193.5,3.759,20.9,22.0,4.176216,0
137,Toyota,RAV4,25.106,1,16.888,2.0,127,94.9,66.7,163.8,2.668,15.3,27.0,3.223107,0
138,Toyota,4Runner,68.411,1,22.288,2.7,150,105.3,66.5,183.3,3.440,18.5,23.0,4.225534,0
139,Toyota,Land Cruiser,9.835,1,51.728,4.7,230,112.2,76.4,192.5,5.115,25.4,15.0,2.285947,0
140,Volkswagen,Golf,9.761,0,14.900,2.0,115,98.9,68.3,163.3,2.767,14.5,26.0,2.278395,0
141,Volkswagen,Jetta,83.721,0,16.700,2.0,115,98.9,68.3,172.3,2.853,14.5,26.0,4.427490,0
142,Volkswagen,Passat,51.102,0,21.200,1.8,150,106.4,68.5,184.1,3.043,16.4,27.0,3.933824,0
143,Volkswagen,Cabrio,9.569,0,19.990,2.0,115,97.4,66.7,160.4,3.079,13.7,26.0,2.258529,0
144,Volkswagen,GTI,5.596,0,17.500,2.0,115,98.9,68.3,163.3,2.762,14.6,26.0,1.722052,0
145,Volkswagen,Beetle,49.463,0,15.900,2.0,115,98.9,67.9,161.1,2.769,14.5,26.0,3.901225,0
146,Volvo,S40,16.957,0,23.400,1.9,160,100.5,67.6,176.6,2.998,15.8,25.0,2.830681,0
147,Volvo,V40,3.545,0,24.400,1.9,160,100.5,67.6,176.6,3.042,15.8,25.0,1.265538,0
148,Volvo,S70,15.245,0,27.500,2.4,168,104.9,69.3,185.9,3.208,17.9,25.0,2.724252,0
149,Volvo,V70,17.531,0,28.800,2.4,168,104.9,69.3,186.2,3.259,17.9,25.0,2.863971,0
150,Volvo,C70,3.493,0,45.500,2.3,236,104.9,71.5,185.7,3.601,18.5,23.0,1.250761,0
151,Volvo,S80,18.969,0,36.000,2.9,201,109.9,72.1,189.8,3.600,21.1,24.0,2.942806,0
152,UD,newCar,0.000,0,21.500,1.5,76,106.3,67.9,175.0,2.932,11.9,46.0,0.000000,1
153,UD,newTruck,0.000,1,34.200,3.5,167,109.8,75.2,188.4,4.508,17.2,26.0,0.000000,1

In [32]:
data = data[data['type']==1] ## type=1인 것만 골라내기

In [37]:
old_data = data[data['manufact']!="UD"].drop(['model','sales','lnsales','Partition','type'],1)
newTruck = data[data['manufact']=="UD"].drop(['model','sales','lnsales','Partition','type'],1).drop(['manufact'],1)

In [38]:
old_data

,manufact,price,engine_s,horsepow,wheelbas,width,length,curb_wgt,fuel_cap,mpg
16,Cadillac,46.225,5.7,255,117.5,77.0,201.2,5.572,30.0,15.0
36,Dodge,19.460,5.2,230,138.7,79.3,224.2,4.470,26.0,17.0
37,Dodge,21.315,3.9,175,109.6,78.8,192.6,4.245,32.0,15.0
38,Dodge,18.575,3.9,175,127.2,78.8,208.5,4.298,32.0,16.0
39,Dodge,16.980,2.5,120,131.0,71.5,215.0,3.557,22.0,19.0
40,Dodge,26.310,5.2,230,115.7,71.7,193.5,4.394,25.0,17.0
41,Dodge,19.565,2.4,150,113.3,76.8,186.3,3.533,20.0,24.0
48,Ford,31.930,4.0,210,111.6,70.2,190.7,3.876,21.0,19.0
49,Ford,21.410,3.0,150,120.7,76.6,200.9,3.761,26.0,21.0
50,Ford,36.135,4.6,240,119.0,78.7,204.6,4.808,26.0,16.0
51,Ford,12.050,2.5,119,117.5,69.4,200.7,3.086,20.0,23.0
52,Ford,26.935,4.6,220,138.5,79.1,224.5,4.241,25.1,18.0
55,Honda,20.550,2.0,146,103.2,68.9,177.6,3.219,15.3,24.0
56,Honda,26.600,3.2,205,106.4,70.4,178.2,3.857,21.1,19.0
57,Honda,26.000,3.5,210,118.1,75.6,201.2,4.288,20.0,23.0
63,Jeep,14.460,2.5,120,93.4,66.7,152.0,3.045,19.0,17.0
64,Jeep,21.620,4.0,190,101.4,69.4,167.5,3.194,20.0,20.0
65,Jeep,26.895,4.0,195,105.9,72.3,181.5,3.880,20.5,19.0
70,Lexus,60.105,4.7,230,112.2,76.4,192.5,5.401,25.4,15.0
71,Lexus,34.605,3.0,220,103.0,71.5,180.1,3.900,17.2,21.0
74,Lincoln,42.660,5.4,300,119.0,79.9,204.8,5.393,30.0,15.0
80,Mitsubishi,31.807,3.5,200,107.3,69.9,186.6,4.520,24.3,18.0
81,Mitsubishi,22.527,3.0,173,107.3,66.7,178.3,3.510,19.5,20.0
86,Mercury,27.560,4.0,210,111.6,70.2,190.1,3.876,21.0,18.0
87,Mercury,22.510,3.3,170,112.2,74.9,194.7,3.944,20.0,21.0
96,Mercedes-Benz,35.300,3.2,215,111.0,72.2,180.6,4.387,19.0,20.0
100,Nissan,26.399,3.3,170,112.2,74.9,194.8,3.991,20.0,21.0
101,Nissan,29.299,3.3,170,106.3,71.7,182.6,3.947,21.0,19.0
102,Nissan,22.799,3.3,170,104.3,70.4,178.0,3.821,19.4,18.0
103,Nissan,17.890,3.3,170,116.1,66.5,196.1,3.217,19.4,18.0
107,Oldsmobile,31.598,4.3,190,107.0,67.8,181.2,4.068,17.5,19.0
108,Oldsmobile,25.345,3.4,185,120.0,72.2,201.4,3.948,25.0,22.0
111,Plymouth,18.850,2.4,150,113.3,76.8,186.3,3.528,20.0,24.0
118,Pontiac,25.635,3.4,185,120.0,72.7,201.3,3.942,25.0,23.0
130,Subaru,20.095,2.5,165,99.4,68.3,175.2,3.125,15.9,24.0
135,Toyota,11.528,2.4,142,103.3,66.5,178.7,2.580,15.1,23.0
136,Toyota,22.368,3.0,194,114.2,73.4,193.5,3.759,20.9,22.0
137,Toyota,16.888,2.0,127,94.9,66.7,163.8,2.668,15.3,27.0
138,Toyota,22.288,2.7,150,105.3,66.5,183.3,3.440,18.5,23.0
139,Toyota,51.728,4.7,230,112.2,76.4,192.5,5.115,25.4,15.0

In [39]:
X = old_data.drop(['manufact'],1)
y = old_data['manufact']

In [41]:
KNN_model = KNeighborsClassifier(n_neighbors=5,
                                 metric='euclidean',
                                weights='distance') #가까운 이웃일수록 가중치 둠
KNN_model.fit(X,y)
new_pred = KNN_model.predict(newTruck)
new_pred

array(['Nissan'], dtype=object)

In [94]:
Nissan = data[data['manufact']=="Nissan"].drop(['sales','lnsales','Partition','type'],1)

In [95]:
euc_list = []
v1 = newTruck
for i in Nissan.values:
    v2 = i[2:]
    eu = euclidean(v1,v2)
    print("model:",i[1])
    print(eu)
    print("======================")
    euc_list.append(eu)
print("최소 유사도 거리:",min(euc_list))

model: Sentra
49.28801706297384
======================
model: Altima
21.141525867354048
======================
model: Maxima
55.88651176267848
======================
model: Quest
12.239807596527005
======================
model: Pathfinder
12.448073023564739
======================
model: Xterra
19.229788610382595
======================
model: Frontier
22.808611991964785
======================
최소 유사도 거리: 12.239807596527005